GPU: 0
b1: 0.5
b2: 0.999
batch_size: 1
datasets_folder: my_experiment
datasets_path: datasets
epoch: 0
gap_h: 32
gap_s: 60
gap_w: 32
img_h: 64
img_s: 150
img_w: 64
lr: 0.001
n_epochs: 15
normalize_factor: 65535
output_dir: ./results
train_datasets_size: 4000
